name: Frontend CI/CD

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache yarn dependencies
        uses: actions/cache@v3.3.0
        id: cache-dependencies
        with:
          path: front/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          cd front
          yarn install --force --non-interactive

  build:
    name: Building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    needs: install-cache
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore yarn dependencies
        uses: actions/cache@v3.3.0
        id: cache-dependencies
        with:
          path: front/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build project
        run: | 
            cd front
            yarn build

  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    needs: [install-cache, build]
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore yarn dependencies
        uses: actions/cache@v3.3.0
        id: cache-dependencies
        with:
          path: front/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Test project
        run: |
            cd front
            yarn test